"use client";

import { createContext, useContext, useEffect, useState } from "react";

const translations = {
  en: {
    subheadline: "No calling ahead, no walk in gamble, just held, for you.",
    searchPlaceholder: "Search restaurant or cuisine",
    loadingRestaurants: "Loading restaurants…",
    noRestaurants: "No restaurants yet — check back soon.",
    trialPartner: "Trial partner",
    back: "Back",
    menuHighlights: "Menu highlights",
    availableTonight: "Available tonight",
    noMenuItems: "No menu items added yet.",
    reserveTable: "Continue",
    reserveAt: "Reserve at",
    partySize: "Party size",
    date: "Date",
    timeTonight: "Time",
    celebrating: "Celebrating anything?",
    occasionNone: "None",
    occasionBirthday: "Birthday",
    occasionAnniversary: "Anniversary",
    occasionBusiness: "Business",
    yourName: "Your name",
    fullName: "Full name",
    mobileNumber: "Mobile number",
    continueSeating: "Hold my table",
    whereSit: "Where would you like to sit?",
    continueSecure: "Continue to secure table",
    secureTable: "Secure your table",
    holdsTable: "holds this table for you. A card is required — you're only charged if you don't show up.",
    holdsTableNoCard: "holds this table for you. No card required — this restaurant doesn't charge a no-show fee.",
    noShowFeeLabel: "No-show fee: AED {fee} per guest.",
    freeCancelLabel: "Free to cancel up to {hours} hours before your booking.",
    cardNumber: "Card number",
    confirmHold: "Confirm & hold table",
    cardDisclaimer: "Card is captured as text here for the prototype. Swap this input for Stripe Elements before going live — never send raw card numbers to your own database.",
    tableRequested: "Table requested",
    hasBeenNotified: "has been notified and will confirm shortly.",
    seating: "Seating",
    time: "Time",
    occasion: "Occasion",
    shareFriends: "Share with friends",
    done: "Done",
    myBookings: "My Bookings",
    myBookingsEmpty: "Nothing here yet, book a table, or open a link a friend shared with you.",
    awaitingConfirmation: "Awaiting confirmation",
    cancelled: "Cancelled",
    share: "Share",
    cancelReservation: "Cancel reservation",
    cancelRequest: "Cancel request",
    confirmCancelReservation: "Cancel this reservation? The restaurant will be notified right away.",
    confirmCancelRequest: "Cancel this request? The restaurant will be notified right away.",
    remove: "Remove",
    discover: "Discover",
    indoor: "Indoor",
    outdoor: "Outdoor",
    shishaTerrace: "Shisha Terrace",
    shishaDesc: "Open-air, may carry a minimum spend",
    outdoorDesc: "Al fresco seating",
    indoorDesc: "Climate-controlled dining room",
    fullyBooked: "Fully booked at this time",
    zoneJustFilled: "{zone} just filled up for this time. Please choose another zone or time.",
    currentBookings: "Current",
    pastBookings: "Past",
    pastBookingsEmpty: "No past reservations yet.",
    declined: "Declined",
    noShowStatus: "No-show",
    dined: "Dined",
    tablesLeft: "{count} left",
    slotFull: "Full",
    partySizeHint: "Enter your exact group size — we'll seat you at the right table.",
    partySizeMaxNote: "For groups larger than {max}, please contact the restaurant directly.",
    confirmedStatus: "Confirmed",
    heldStatus: "Held",
    edit: "Edit",
    editReservation: "Edit reservation at",
    editWindowClosed: "This booking is too close to its time to edit — within {hours} hours. Please contact the restaurant directly.",
    sendChangeRequest: "Send change request",
    editedStatus: "Edited",

    // Restaurant dashboard / settings / login
    loading: "Loading…",
    partnerLogin: "Partner login",
    signInSubtitle: "Sign in to manage your restaurant.",
    signUpSubtitle: "Create your restaurant account.",
    restaurantNamePlaceholder: "e.g. Ember & Vine",
    email: "Email",
    password: "Password",
    pleaseWait: "Please wait…",
    signIn: "Sign in",
    createAccount: "Create account",
    newRestaurantSignUp: "New restaurant? Create an account",
    haveAccountSignIn: "Already have an account? Sign in",
    partnerDashboard: "Partner dashboard",
    settingsLabel: "Settings",
    signOut: "Sign out",
    noRestaurantLinked: "No restaurant is linked to your account yet. If you believe this is a mistake, contact support.",
    freeTrial: "Free trial",
    activeSubscription: "Active subscription",
    needsResponseTab: "Needs Response",
    historyTab: "History",
    noNewRequests: "No new requests right now.",
    guestsCount: "{count} guests",
    noConfirmedYet: "No confirmed bookings yet.",
    markDined: "Mark as Dined",
    markNoShow: "Mark no-show",
    noHistoryYet: "No booking history yet.",
    chargedNoShows: "Charged no-shows",
    chargedAed: "Charged AED {amount}",
    restaurantKeepsFee: "Restaurant keeps AED {keep} · Held fee AED {fee}",
    dismiss: "Dismiss",
    cancelledByGuest: "Cancelled by guest",
    tableFreed: "table freed",
    restaurantSettings: "Restaurant settings",
    setUpRestaurant: "Set up your restaurant",
    onboardingSubtitle: "Tell diners what to expect — this is what they'll see before booking.",
    settingsSubtitle: "Update this anytime — prices, seating, and details go live immediately.",
    skipForNow: "Skip for now",
    backToDashboard: "Back to dashboard",
    restaurantName: "Restaurant name",
    cuisine: "Cuisine",
    cuisinePlaceholder: "e.g. Modern European",
    area: "Area",
    areaPlaceholder: "e.g. DIFC",
    priceTier: "Price tier",
    advanceBookingQuestion: "How far ahead can diners book?",
    minNoticeDays: "Minimum notice (days)",
    maxWindowDays: "Maximum window (days)",
    advanceBookingHint: "0 minimum means same-day bookings are allowed. E.g. 0 to 30 lets diners book anywhere from tonight to a month out.",
    bookingHours: "Booking hours",
    to: "to",
    bookingHoursHint: "This is the window diners can pick a time slot within, in 30-minute steps.",
    maxPartySizeLabel: "Largest group you can seat online",
    maxPartySizeHint: "Diners can request any group size up to this number. Beyond it, they'll be told to contact you directly.",
    tableSizesOffered: "Table sizes you offer",
    seatingAvailable: "Seating available",
    tablesUnit: "tables",
    zoneCapacityHint: "How many tables you have in each area. Diners will see a zone as fully booked once all its tables are taken for a given time.",
    noShowFeeSetting: "No-show fee (AED per guest)",
    cancellationWindowSetting: "Free cancellation window (hours before booking)",
    saved: "Saved!",
    saving: "Saving…",
    finishSetup: "Finish setup",
    saveChanges: "Save changes",
    menu: "Menu",
    menuSectionHint: "Add the dishes diners see on your listing. Changes here save immediately.",
    addADish: "Add a dish",
    dishNamePlaceholder: "Dish name",
    aedPlaceholder: "AED",
    adding: "Adding…",
    addDish: "Add dish",
    deleteDish: "Delete dish",
    save: "Save",
    cancel: "Cancel",
  },
  ar: {
    subheadline: "بدون اتصال مسبق، بدون مقامرة الحضور المباشر، فقط محجوزة لك.",
    searchPlaceholder: "ابحث عن مطعم أو نوع مأكولات",
    loadingRestaurants: "جاري تحميل المطاعم…",
    noRestaurants: "لا توجد مطاعم بعد — تحقق قريبًا.",
    trialPartner: "شريك تجريبي",
    back: "رجوع",
    menuHighlights: "أبرز أطباق القائمة",
    availableTonight: "المتاح الليلة",
    noMenuItems: "لم تتم إضافة أطباق بعد.",
    reserveTable: "متابعة",
    reserveAt: "احجز في",
    partySize: "عدد الضيوف",
    date: "التاريخ",
    timeTonight: "الوقت",
    celebrating: "هل تحتفلون بمناسبة؟",
    occasionNone: "لا شيء",
    occasionBirthday: "عيد ميلاد",
    occasionAnniversary: "ذكرى سنوية",
    occasionBusiness: "عمل",
    yourName: "اسمك",
    fullName: "الاسم الكامل",
    mobileNumber: "رقم الجوال",
    continueSeating: "احجز طاولتي",
    whereSit: "أين تودون الجلوس؟",
    continueSecure: "متابعة لتأكيد الطاولة",
    secureTable: "أكد طاولتك",
    holdsTable: "يحجز لك هذه الطاولة. مطلوب بطاقة — لن يتم خصم أي مبلغ إلا في حال عدم الحضور.",
    holdsTableNoCard: "يحجز لك هذه الطاولة. لا حاجة لبطاقة — هذا المطعم لا يفرض رسوم عدم حضور.",
    noShowFeeLabel: "رسوم عدم الحضور: {fee} درهم لكل ضيف.",
    freeCancelLabel: "يمكن الإلغاء مجانًا حتى {hours} ساعة قبل موعد الحجز.",
    cardNumber: "رقم البطاقة",
    confirmHold: "تأكيد وحجز الطاولة",
    cardDisclaimer: "بيانات البطاقة هنا لأغراض العرض التجريبي فقط. يجب استبدالها بـ Stripe قبل الإطلاق الفعلي — لا تُرسل أرقام البطاقات الحقيقية إلى قاعدة بياناتك الخاصة أبدًا.",
    tableRequested: "تم طلب الطاولة",
    hasBeenNotified: "تم إشعاره وسيقوم بالتأكيد قريبًا.",
    seating: "الجلسة",
    time: "الوقت",
    occasion: "المناسبة",
    shareFriends: "شارك مع الأصدقاء",
    done: "تم",
    myBookings: "حجوزاتي",
    myBookingsEmpty: "لا يوجد شيء هنا بعد، احجز طاولة، أو افتح رابطًا شاركه معك صديق.",
    awaitingConfirmation: "بانتظار التأكيد",
    cancelled: "ملغى",
    share: "مشاركة",
    cancelReservation: "إلغاء الحجز",
    cancelRequest: "إلغاء الطلب",
    confirmCancelReservation: "هل تريد إلغاء هذا الحجز؟ سيتم إشعار المطعم فورًا.",
    confirmCancelRequest: "هل تريد إلغاء هذا الطلب؟ سيتم إشعار المطعم فورًا.",
    remove: "إزالة",
    discover: "استكشف",
    indoor: "داخلي",
    outdoor: "خارجي",
    shishaTerrace: "تراس الشيشة",
    shishaDesc: "جلسة مفتوحة، قد يُشترط حد أدنى للإنفاق",
    outdoorDesc: "جلسة خارجية",
    indoorDesc: "قاعة مكيفة",
    fullyBooked: "محجوز بالكامل في هذا الوقت",
    zoneJustFilled: "{zone} امتلأ للتو في هذا الوقت. الرجاء اختيار جلسة أو وقت آخر.",
    currentBookings: "الحالية",
    pastBookings: "السابقة",
    pastBookingsEmpty: "لا توجد حجوزات سابقة بعد.",
    declined: "مرفوض",
    noShowStatus: "عدم حضور",
    dined: "تم الحضور",
    tablesLeft: "{count} متبقٍ",
    slotFull: "ممتلئ",
    partySizeHint: "أدخل عدد أفراد مجموعتك بالضبط — سنجهز لكم الطاولة المناسبة.",
    partySizeMaxNote: "للمجموعات الأكبر من {max}، يُرجى التواصل مع المطعم مباشرة.",
    confirmedStatus: "مؤكد",
    heldStatus: "محجوز",
    edit: "تعديل",
    editReservation: "تعديل الحجز في",
    editWindowClosed: "هذا الحجز قريب جدًا من موعده للتعديل — خلال {hours} ساعة. يُرجى التواصل مع المطعم مباشرة.",
    sendChangeRequest: "إرسال طلب التعديل",
    editedStatus: "معدّل",

    // Restaurant dashboard / settings / login
    loading: "جارٍ التحميل…",
    partnerLogin: "تسجيل دخول الشريك",
    signInSubtitle: "سجّل الدخول لإدارة مطعمك.",
    signUpSubtitle: "أنشئ حساب مطعمك.",
    restaurantNamePlaceholder: "مثال: مطعم الحديقة",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    pleaseWait: "يرجى الانتظار…",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    newRestaurantSignUp: "مطعم جديد؟ أنشئ حسابًا",
    haveAccountSignIn: "لديك حساب بالفعل؟ سجّل الدخول",
    partnerDashboard: "لوحة تحكم الشريك",
    settingsLabel: "الإعدادات",
    signOut: "تسجيل الخروج",
    noRestaurantLinked: "لا يوجد مطعم مرتبط بحسابك بعد. إذا كنت تعتقد أن هذا خطأ، يرجى التواصل مع الدعم.",
    freeTrial: "نسخة تجريبية مجانية",
    activeSubscription: "اشتراك نشط",
    needsResponseTab: "بحاجة للرد",
    historyTab: "السجل",
    noNewRequests: "لا توجد طلبات جديدة الآن.",
    guestsCount: "{count} ضيوف",
    noConfirmedYet: "لا توجد حجوزات مؤكدة بعد.",
    markDined: "تحديد كحاضر",
    markNoShow: "تحديد كعدم حضور",
    noHistoryYet: "لا يوجد سجل حجوزات بعد.",
    chargedNoShows: "حالات عدم الحضور المحصّلة",
    chargedAed: "تم تحصيل {amount} درهم",
    restaurantKeepsFee: "يحتفظ المطعم بـ {keep} درهم · رسوم هيلد {fee} درهم",
    dismiss: "إخفاء",
    cancelledByGuest: "ألغاها الضيف",
    tableFreed: "الطاولة أصبحت متاحة",
    restaurantSettings: "إعدادات المطعم",
    setUpRestaurant: "إعداد مطعمك",
    onboardingSubtitle: "أخبر الزوار بما يمكن توقعه — هذا ما سيرونه قبل الحجز.",
    settingsSubtitle: "حدّث هذا في أي وقت — الأسعار والجلسات والتفاصيل تُنشر فورًا.",
    skipForNow: "تخطَّ الآن",
    backToDashboard: "العودة إلى لوحة التحكم",
    restaurantName: "اسم المطعم",
    cuisine: "نوع المطبخ",
    cuisinePlaceholder: "مثال: أوروبي حديث",
    area: "المنطقة",
    areaPlaceholder: "مثال: مركز دبي المالي",
    priceTier: "الفئة السعرية",
    advanceBookingQuestion: "إلى متى مسبقًا يمكن للزوار الحجز؟",
    minNoticeDays: "الحد الأدنى للإشعار (أيام)",
    maxWindowDays: "الحد الأقصى للنافذة (أيام)",
    advanceBookingHint: "0 كحد أدنى يعني السماح بالحجز في نفس اليوم. مثال: من 0 إلى 30 يتيح للزوار الحجز من الليلة حتى شهر مقدمًا.",
    bookingHours: "ساعات الحجز",
    to: "إلى",
    bookingHoursHint: "هذه هي الفترة التي يمكن للزوار اختيار موعد ضمنها، بفواصل 30 دقيقة.",
    maxPartySizeLabel: "أكبر عدد ضيوف يمكنك استقبالهم عبر الإنترنت",
    maxPartySizeHint: "يمكن للزوار طلب أي عدد ضيوف حتى هذا الرقم. وما بعده، سيُطلب منهم التواصل معك مباشرة.",
    tableSizesOffered: "أحجام الطاولات المتوفرة",
    seatingAvailable: "الجلسات المتاحة",
    tablesUnit: "طاولات",
    zoneCapacityHint: "عدد الطاولات المتوفرة في كل منطقة. سيرى الزوار المنطقة على أنها محجوزة بالكامل بمجرد أن تُشغل جميع طاولاتها في وقت معين.",
    noShowFeeSetting: "رسوم عدم الحضور (درهم لكل ضيف)",
    cancellationWindowSetting: "فترة الإلغاء المجاني (ساعات قبل الحجز)",
    saved: "تم الحفظ!",
    saving: "جارٍ الحفظ…",
    finishSetup: "إنهاء الإعداد",
    saveChanges: "حفظ التغييرات",
    menu: "القائمة",
    menuSectionHint: "أضف الأطباق التي يراها الزوار في صفحتك. التغييرات هنا تُحفظ فورًا.",
    addADish: "إضافة طبق",
    dishNamePlaceholder: "اسم الطبق",
    aedPlaceholder: "درهم",
    adding: "جارٍ الإضافة…",
    addDish: "إضافة الطبق",
    deleteDish: "حذف الطبق",
    save: "حفظ",
    cancel: "إلغاء",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("masa_lang");
    if (saved === "ar" || saved === "en") {
      setLang(saved);
    }
  }, []);

  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
    window.localStorage.setItem("masa_lang", lang);
  }, [lang]);

  function t(key, vars) {
    let str = translations[lang]?.[key] || translations.en[key] || key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
    }
    return str;
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
